name: Buildah

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*-b*

jobs:
  build_and_push:
    name: Build container and push to GHCR and Docker registries.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v') && contains(github.ref, '.')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if tag matches pattern
        id: tag_pattern
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+$ ]]; then
            echo "Tag [${{ github.ref_name }}] matches the vX.X.X-bX pattern."
          else
            echo "Tag [${{ github.ref_name }}] does NOT match the vX.X.X-bX pattern. Exiting."
            exit 1
          fi
          version=$(echo "${{ github.ref_name }}" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "tag=${version}" | tee -a $GITHUB_OUTPUT
          echo "build=$(echo "${version}" | sed -E 's/.*-b([0-9]+).*/b\1/;t;d')" | tee -a $GITHUB_OUTPUT
          echo "datecode=$(date '+%y%m%d')" | tee -a $GITHUB_OUTPUT

      - name: Download QLC Release
        run: curl -fsSL https://www.qlcplus.org/downloads/${{ steps.tag_pattern.outputs.tag }}/qlcplus_${{ steps.tag_pattern.outputs.tag }}_amd64.deb --output qlcplus.deb
       
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: #{{ secrets.DOCKER_USERNAME }}
      #     password: #{{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},suffix=-${{ steps.tag_pattern.outputs.build }}.${{ steps.tag_pattern.outputs.datecode }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ steps.tag_pattern.outputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.tag_pattern.outputs.tag }}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }},value=${{ steps.tag_pattern.outputs.tag }}
            type=semver,pattern={{major}}-latest,value=${{ steps.tag_pattern.outputs.tag }}

      - name: Debug Container Meta outputs
        run:   echo "$OUTPUTS"
        shell: bash
        env:
          OUTPUTS: ${{ toJSON(steps.meta.outputs) }}

      # - name: Buildah Action
      #   uses: redhat-actions/buildah-build@v2
      #   with:
      #     image: ghcr.io/${{ github.repository }}
      #     tags: v1 ${{ github.sha }}
      #     containerfiles: |
      #       ./Containerfile
      #     build-args: |
      #       some_arg=some_value

      - name: Delete tag [${{ github.ref_name }}] on failure
        if: failure()
        run: |
          echo "Deleting tag: ${{ github.ref_name }}"
          git tag -d "${{ github.ref_name }}"
          git push origin ":${{ github.ref_name }}"
    