name: Buildah

on:
  workflow_dispatch:
  push:
    tags:
      # v#.#.#-b+YYMMDD.{BUILD_INDEX}
      - v*.*.*-b+*.*

jobs:
  build_and_push:
    name: Build container and push to GHCR and Docker registries.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v') && contains(github.ref, '.')
    steps:
      - name: Check if tag matches pattern
        id: tag_pattern
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-b\+[0-9]{6}\.[0-9]+$ ]]; then
            echo "Tag [${{ github.ref_name }}] matches the v#.#.#-b+YYMMDD.# pattern."
          else
            echo "Tag [${{ github.ref_name }}] does NOT match the v#.#.#-b+YYMMDD.# pattern. Exiting."
            exit 1
          fi
          echo "tag=$(echo "${{ github.ref_name }}" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')" | tee -a $GITHUB_OUTPUT
          echo "build=b$(echo "${{ github.ref_name }}" | sed -n -E 's/.*-b\+([0-9]{6}\.[0-9]+).*/\1/p')" | tee -a $GITHUB_OUTPUT
          echo "datecode=$(date '+%y%m%d')" | tee -a $GITHUB_OUTPUT

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download QLC Release
        run: curl -fsSL https://www.qlcplus.org/downloads/${{ steps.tag_pattern.outputs.tag }}/qlcplus_${{ steps.tag_pattern.outputs.tag }}_amd64.deb --output qlcplus.deb
       
      - name: Log in to Docker Hub
        if: ${{ env.USERNAME != '' && env.PASSWORD != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.tag_pattern.outputs.tag }},suffix=-${{ steps.tag_pattern.outputs.build }}
            type=semver,pattern={{version}},value=${{ steps.tag_pattern.outputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.tag_pattern.outputs.tag }}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }},value=${{ steps.tag_pattern.outputs.tag }}
            type=semver,pattern={{major}}-latest,value=${{ steps.tag_pattern.outputs.tag }}

      - name: Debug Container Meta outputs
        run:   echo "$OUTPUTS"
        shell: bash
        env:
          OUTPUTS: ${{ toJSON(steps.meta.outputs) }}

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/${{ github.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: ./Containerfile
          build-args: |
            VERSION=${{ steps.tag_pattern.outputs.tag }}
            BUILD=${{ steps.tag_pattern.outputs.build }}

      - name: Delete tag [${{ github.ref_name }}] on failure
        if: failure()
        run: |
          echo "Deleting tag: ${{ github.ref_name }}"
          git tag -d "${{ github.ref_name }}"
          git push origin ":${{ github.ref_name }}"
    