name: Buildah

on:
  workflow_dispatch:
  push:
    tags:
      # v#.#.#-b+YYMMDD.{BUILD_INDEX}
      - v*.*.*-b+*.*

jobs:
  build_and_push:
    name: Build container and push to GHCR and Docker registries.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v') && contains(github.ref, '.')
    steps:
      - name: Check if tag matches pattern
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-b\+[0-9]{6}\.[0-9]+$ ]]; then
            echo "Tag [${{ github.ref_name }}] matches the v#.#.#-b+YYMMDD.# pattern."
          else
            echo "Tag [${{ github.ref_name }}] does NOT match the v#.#.#-b+YYMMDD.# pattern. Exiting."
            exit 1
          fi
      
      - name: Split Tag semver parts
        id: semver
        run: |
          # Extract major, minor, patch, build
          if [[ "${{ github.ref_name }}" =~ v([0-9]+)\.([0-9]+)\.([0-9]+)-b\+([0-9]+)\.([0-9]+) ]]; then
              major="${BASH_REMATCH[1]}"
              minor="${BASH_REMATCH[2]}"
              patch="${BASH_REMATCH[3]}"
              datecode="${BASH_REMATCH[4]}"
              build="${BASH_REMATCH[5]}"
              
              echo "version=$major.$minor.$patch" | tee -a $GITHUB_OUTPUT
              echo "major=$major" | tee -a $GITHUB_OUTPUT
              echo "minor=$minor" | tee -a $GITHUB_OUTPUT
              echo "patch=$patch" | tee -a $GITHUB_OUTPUT
              echo "datecode=$datecode" | tee -a $GITHUB_OUTPUT
              echo "build=$build" | tee -a $GITHUB_OUTPUT
          else
              echo "Version format [${{ github.ref_name }}] not recognized."
              exit 1
          fi

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download QLC Release
        run: curl -fsSL https://www.qlcplus.org/downloads/${{ steps.semver.outputs.version }}/qlcplus_${{ steps.semver.outputs.version }}_amd64.deb --output qlcplus.deb
       
      - name: Log in to Docker Hub
        if: ${{ env.USERNAME != '' && env.PASSWORD != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Container
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          tags: |
            type=semver,pattern={{version}},value=${{ steps.semver.outputs.version }},suffix=-b${{ steps.semver.outputs.datecode }}.${{ steps.semver.outputs.build }}
            type=semver,pattern={{version}},value=${{ steps.semver.outputs.version }},suffix=-b${{ steps.semver.outputs.datecode }}
            type=semver,pattern={{version}},value=${{ steps.semver.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.semver.outputs.version }}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }},value=${{ steps.semver.outputs.version }}
            type=semver,pattern={{major}}-latest,value=${{ steps.semver.outputs.version }}

      - name: Debug Container Meta outputs
        run:   echo "$OUTPUTS"
        shell: bash
        env:
          OUTPUTS: ${{ toJSON(steps.meta.outputs) }}

      - name: Buildah Action
        id: buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: ./v${{ steps.semver.outputs.major }}.Containerfile
          build-args: |
            VERSION=${{ steps.semver.outputs.version }}
            BUILD=b${{ steps.semver.outputs.datecode }}.${{ steps.semver.outputs.build }}
            REPO_VERSION=23.04
      
      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push To ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ghcr.io/${{ steps.buildah.outputs.image }}
          tags: ${{ steps.buildah.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Github image url
        run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
      
      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push To docker hub
        if: ${{ env.USERNAME != '' && env.PASSWORD != '' }}
        id: push-to-hub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: docker.io/${{ steps.buildah.outputs.image }}
          tags: ${{ steps.buildah.outputs.tags }}
          registry: docker.io
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Print Docker Hub image url
        if: ${{ env.USERNAME != '' && env.PASSWORD != '' }}
        run: echo "Image pushed to ${{ steps.push-to-hub.outputs.registry-paths }}"
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
            

      - name: Delete tag [${{ github.ref_name }}] on failure
        if: failure()
        run: |
          echo "Deleting tag: ${{ github.ref_name }}"
          git tag -d "${{ github.ref_name }}"
          git push origin ":${{ github.ref_name }}"
    