name: Buildah

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*.*

jobs:
  build_and_push:
    name: Build container and push to GHCR and Docker registries.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v') && contains(github.ref, '.')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if tag matches pattern
        run: |
          if [[ "${{ github.ref_name }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag [${{ github.ref_name }}] matches the vX.X.X.X pattern."
          else
            echo "Tag [${{ github.ref_name }}] does NOT match the vX.X.X.X pattern. Exiting."
            exit 1
          fi

      - name: Download QLC Release
        uses: Minionguyjpro/Download-File-Action@v1
        with:
          url: https://www.qlcplus.org/downloads/$VERSION/qlcplus_$VERSION_amd64.deb
          path: qlcplus.deb
      
      - name: Get daily build suffix
        id: get_build_suffix
        run: echo "tag=$(date '+%y%m%d')" >> $GITHUB_OUTPUT
            
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: #{{ secrets.DOCKER_USERNAME }}
      #     password: #{{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}-${{ steps.get_latest_tag.outputs.LATEST_TAG }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern,enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}={{major}}
            type=semver,pattern={{major}}-latest

      - name: Debug Container Meta outputs
        run:   echo "$OUTPUTS"
        shell: bash
        env:
          OUTPUTS: ${{ toJSON(steps.meta.outputs) }}

      # - name: Buildah Action
      #   uses: redhat-actions/buildah-build@v2
      #   with:
      #     image: ghcr.io/${{ github.repository }}
      #     tags: v1 ${{ github.sha }}
      #     containerfiles: |
      #       ./Containerfile
      #     build-args: |
      #       some_arg=some_value
    